user-message: ! 'Warning (added by new or init): Some packages were found to be incompatible
  with the resolver and have been left commented out in the packages section.

  You can suppress this message by removing it from stack.yaml

'

resolver: lts-6.2

packages: []
extra-deps: []
flags: {}

extra-package-dbs: []
