flags: {}
nix:
  pure: false
  shell-file: default.nix
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Boolean-0.2.3
- MemoTrie-0.6.4
- NumInstances-1.4
- data-reify-0.6.1
- vector-space-0.10.3
resolver: ghc-8.0.1
